<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>htm</string>
		<string>html</string>
		<string>hcsp</string>
		<string>hcst</string>
		<string>idoc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\bdynamichtml\b(\w*)</string>
	<key>foldingStopMarker</key>
	<string>\s*end\s*$</string>
	<key>name</key>
	<string>HTML (Idoc)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#idoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>override HTML comment block patterns to allow Idoc inside</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.block.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-idoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-idoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#idoc</string>
				</dict>
			</array>
		</dict>
		<key>idoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[&lt;\[](!--)?\$\s*\b([cC]|comment)\s?\=\s?"</string>
					<key>comment</key>
					<string>idoc fake comments (XML valid ones)</string>
					<key>end</key>
					<string>"\s*(--|\$)[\]&gt;]</string>
					<key>name</key>
					<string>comment.block.idoc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;\$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>standard delimiters</string>
					<key>end</key>
					<string>(\$&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.idoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-angle-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal-square-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.idoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!--\$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML/XML angle delimiters</string>
					<key>end</key>
					<string>--&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.idoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-xml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal-square-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.idoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[!--\$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML/XML square delimiters</string>
					<key>end</key>
					<string>--\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.idoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-xml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal-angle-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.idoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;@)\s*(dynamichtml|dynamicdata|table|end)\b(\s*[a-zA-Z_]\w*)?\s*([\w\s]*)?\s?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.include.idoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.include.idoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.include.garbage</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>dynamic HTML delimiters</string>
					<key>end</key>
					<string>@&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.idoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-xml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal-angle-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.idoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;@)\s?(.*?)(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.key.localised.string</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.localised.string</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Localised string definition</string>
					<key>end</key>
					<string>@&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.localised.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#illegal-angle-end</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#localised-string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[\[%</string>
					<key>comment</key>
					<string>Idoc comments (non XML)</string>
					<key>end</key>
					<string>%\]\]</string>
					<key>name</key>
					<string>comment.block.idoc</string>
				</dict>
			</array>
		</dict>
		<key>illegal-angle-end</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--&gt;</string>
					<key>name</key>
					<string>invalid.illegal.end-delim</string>
				</dict>
			</array>
		</dict>
		<key>illegal-square-end</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--\]</string>
					<key>name</key>
					<string>invalid.illegal.end-delim</string>
				</dict>
			</array>
		</dict>
		<key>illegal-xml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>These operators are illegal in XML compliant site studio templates and can cause issues.</string>
					<key>match</key>
					<string>&lt;=|&gt;=|&lt;|&gt;|&amp;</string>
					<key>name</key>
					<string>invalid.illegal.xml-entities</string>
				</dict>
			</array>
		</dict>
		<key>localised-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{[0-9]+\}</string>
					<key>name</key>
					<string>constant.character.parameter.localised.string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.idoc</string>
	<key>uuid</key>
	<string>c2ca286d-e38c-43a0-9070-8ec546703fe6</string>
</dict>
</plist>
