<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>idoc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\s*(dynamichtml)\s*([a-zA-Z_]*)\s*</string>
	<key>foldingStopMarker</key>
	<string>\s*end\s*$</string>
	<key>name</key>
	<string>Idoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|else|elseif|endif|loop|loopwhile|endloop|exec|break|not)\b</string>
			<key>name</key>
			<string>keyword.control.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|%|\*|\-|\+|==|=|!=|&lt;=|&gt;=|&lt;|&gt;|&amp;&amp;|&amp;|\b(gt|lt|le|ge|and|or|include|join)\b</string>
			<key>name</key>
			<string>keyword.operator.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|NULL|true|false|TRUE|FALSE|CURRENT_ROW)\b|(\#numRows|\#row|\#isRowPresent|\#isEmpty)\b</string>
			<key>name</key>
			<string>constant.language.idoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b([cC]|comment)\s?\=\s?"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>comment.fake.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(inc|toInteger|rsSort|rsFirst|rsNext|rsRemove|rsRename|strLength|idcbegindata|idcenddata|strEquals|isTrue|executeService|rsAppendNewRow|getValue|setValue|rsCreateResultSet|rsExists|rsMakeFromString|strIndexOf|userHasRole|rsSortTree|wfAddActionHistoryEvent|wfAddUser|wfComputeStepUserList|wfCurrentGet|wfCurrentSet|wfCurrentStep|wfDisplayCondition|wfExit|wfGet|wfIsFinishedDocConversion|wfIsNotifyingUsers|wfIsReleasable|wfLoadDesign|wfNotify|wfSet|wfSetIsNotifyingUsers|wfUpdateMetaData|wfAction|wfMessage|dWfName|dWfStepName|wfAction|wfAdditionalExitCondition|wfGetStepTypeLabel|wfMailSubject|wfMessage|wfParentList|wfReleaseDocument|WfStart)\b(?=\()</string>
			<key>name</key>
			<string>support.function.core.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(HttpRelativeWebRoot)\b</string>
			<key>name</key>
			<string>support.variable.core.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\#active|\#local|\#env)\b</string>
			<key>name</key>
			<string>support.type.core.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\.?[0-9]*\b</string>
			<key>name</key>
			<string>constant.numeric.idoc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.include.idoc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.include.idoc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(dynamichtml)\s*([a-zA-Z_]\w*)\s*</string>
			<key>name</key>
			<string>meta.include.idoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(end)\b\s*</string>
			<key>name</key>
			<string>support.type.include.idoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(like)\s*"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.like.idoc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.like.idoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-like</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.idoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.idoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\[nrft]</string>
			<key>name</key>
			<string>constant.character.escape.php</string>
		</dict>
		<key>string-like</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.idoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>support.function.like.divider</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.idoc</string>
	<key>uuid</key>
	<string>372f8085-736a-4822-81cb-713c81e1f259</string>
</dict>
</plist>
